spring.application.name=brainbyte

# Configuration BDD MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/brainbyte?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=@msterlyCA002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Désactiver l'initialisation par scripts SQL car on utilise DataInitializer.java
spring.sql.init.mode=never

server.port=8080

# Identifiants Admin
brainbyte.admin.email=admin@brainbyte.ht
brainbyte.admin.password=admin123
