spring.application.name=brainbyte

# Configuration H2 (File mode)
spring.datasource.url=jdbc:h2:file:./data/quizzdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Désactiver l'initialisation par scripts SQL car on utilise DataInitializer.java
spring.sql.init.mode=never

# Port dynamique pour Render / Cloud
server.port=${PORT:8080}

# Identifiants Admin
brainbyte.admin.email=admin@brainbyte.ht
brainbyte.admin.password=admin123
